export enum vendorActionTypes {
  GET_VENDOR_REQUEST = "GET_VENDOR_REQUEST",
  GET_VENDOR_SUCCESS = "GET_VENDOR_SUCCESS",
  GET_VENDOR_FAILURE = "GET_VENDOR_FAILURE",
  LOAD_MORE_VENDOR_REQUEST = "LOAD_MORE_VENDOR_REQUEST",
  LOAD_MORE_VENDOR_SUCCESS = "LOAD_MORE_VENDOR_SUCCESS",
  LOAD_MORE_VENDOR_FAILURE = "LOAD_MORE_VENDOR_FAILURE",
}
